[package]
name = "quake"
version = "0.1.0"
authors = ["Matthew Collins <thethinkofdeath@gmail.com>"]

[dependencies]
byteorder = "1.3.1"
cgmath = "0.17.0"
error-chain = "0.12.0"
gfx = "0.18.0"
gfx_window_glutin = "0.30.0"
glutin = "0.20.0"
env_logger = "0.6.1"
